{% set python_min = "3.10" %}
{% set name = "pyspectral" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 538161a2c4b8aec03b1fce065e6fb874d6a11f8444a47a9319084b0e56b2709e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    # needed for pkg_resources with dynamic setuptools_scm
    - setuptools
    - numpy >=1.5.1
    - scipy >=1.6.0
    - python-geotiepoints >=1.1.1
    - h5py >=2.5
    - requests
    - tqdm
    - pyyaml
    - platformdirs
    - dask

test:
  imports:
    - pyspectral
  requires:
    - dask
    - h5pickle
    - matplotlib-base
    - pyyaml
    - xlrd
    - python {{ python_min }}

about:
  home: https://github.com/pytroll/pyspectral
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Reading and manipulaing satellite sensor spectral responses and the solar spectrum, to perfom various corrections to VIS and NIR band data
  description: pyspectral is a package to read and manipulate satellite sensor spectral responses and solar irradiance spectra
  doc_url: https://pyspectral.readthedocs.io
  dev_url: https://github.com/pytroll/pyspectral

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
