{% set name = "pyspectral" %}
{% set version = "0.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 246bfa1c979f9982fcdcb063d9940819cc11a101a5315d7923eb26b7931d6cc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.10
    # needed for pkg_resources with dynamic setuptools_scm
    - setuptools
    - numpy >=1.5.1
    - scipy >=1.6.0
    - python-geotiepoints >=1.1.1
    - h5py >=2.5
    - requests
    - tqdm
    - pyyaml
    - platformdirs
    - dask

test:
  imports:
    - pyspectral
  requires:
    - dask
    - h5pickle
    - matplotlib-base
    - pyyaml
    - xlrd

about:
  home: https://github.com/pytroll/pyspectral
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Reading and manipulaing satellite sensor spectral responses and the solar spectrum, to perfom various corrections to VIS and NIR band data
  description: pyspectral is a package to read and manipulate satellite sensor spectral responses and solar irradiance spectra
  doc_url: https://pyspectral.readthedocs.io
  dev_url: https://github.com/pytroll/pyspectral

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
