{% set name = "pyspectral" %}
{% set version = "0.8.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fcb7b046b8adfad900814624d1e7c50d61045b8e19a4090b63472fe230ac4182" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - docutils >=0.3
    - numpy >=1.5.1
    - scipy >=0.14
    - python-geotiepoints >=1.1.1
    - h5py >=2.5
    - requests
    - tqdm
    - six
    - pyyaml
    - appdirs
    - dask

test:
  imports:
    - pyspectral
  requires:
    - dask
    - h5pickle
    - matplotlib
    - pyyaml
    - xlrd

about:
  home: https://github.com/pytroll/pyspectral
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Reading and manipulaing satellite sensor spectral responses and the solar spectrum, to perfom various corrections to VIS and NIR band data
  description: pyspectral is a package to read and manipulate satellite sensor spectral responses and solar irradiance spectra
  doc_url: https://pyspectral.readthedocs.io
  dev_url: https://github.com/pytroll/pyspectral

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
